  
language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: 
  - npm run build
  - cp dist/front/index.html dist/front/404.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/front
  on:
    branch: master
notifications:
  email: false